quarkus.http.port=8080
jsonapi4j.rootPath=/test
jsonapi4j.compoundDocs.enabled=true
jsonapi4j.compoundDocs.maxHops=3
jsonapi4j.compoundDocs.mapping.users=http://localhost:${quarkus.http.port}${jsonapi4j.rootPath}
jsonapi4j.compoundDocs.mapping.countries=http://localhost:${quarkus.http.port}${jsonapi4j.rootPath}
jsonapi4j.compoundDocs.mapping.currencies=http://localhost:${quarkus.http.port}${jsonapi4j.rootPath}