package io.jsonapi4j.model.document.error;

public enum DefaultErrorCodes implements ErrorCode {

    GENERIC_REQUEST_ERROR("GENERIC_REQUEST_ERROR"),
    MISSING_REQUIRED_PARAMETER("MISSING_REQUIRED_PARAMETER"),
    MISSING_REQUIRED_HEADER("MISSING_REQUIRED_HEADER"),
    INVALID_ENUM_VALUE("INVALID_ENUM_VALUE"),
    VALUE_IS_ABSENT("VALUE_IS_ABSENT"),
    VALUE_EMPTY("VALUE_EMPTY"),
    VALUE_TOO_SHORT("VALUE_TOO_SHORT"),
    VALUE_TOO_LONG("VALUE_TOO_LONG"),
    VALUE_TOO_HIGH("VALUE_TOO_HIGH"),
    VALUE_TOO_LOW("VALUE_TOO_LOW"),
    VALUE_INVALID_FORMAT("VALUE_INVALID_FORMAT"),
    ARRAY_LENGTH_TOO_SHORT("ARRAY_LENGTH_TOO_SHORT"),
    ARRAY_LENGTH_TOO_LONG("ARRAY_LENGTH_TOO_LONG"),
    CONFLICTING_PARAMETERS("CONFLICTING_PARAMETERS"),
    INVALID_CURSOR("INVALID_CURSOR"),
    INVALID_PAYLOAD("INVALID_PAYLOAD"),

    BAD_GATEWAY("BAD_GATEWAY"),
    CONFLICT("CONFLICT"),
    MAX_AMOUNT_OF_RESOURCES("MAX_AMOUNT_OF_RESOURCES"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    NOT_ACCEPTABLE("NOT_ACCEPTABLE"),
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    METHOD_NOT_SUPPORTED("METHOD_NOT_SUPPORTED"),
    NOT_FOUND("NOT_FOUND"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),

    UNAUTHORIZED("UNAUTHORIZED"),
    ACCESS_TOKEN_REVOKED("ACCESS_TOKEN_REVOKED"),
    ACCESS_TOKEN_EXPIRED("ACCESS_TOKEN_EXPIRED"),
    FORBIDDEN("FORBIDDEN"),
    INSUFFICIENT_SCOPES("INSUFFICIENT_SCOPES"),
    INSUFFICIENT_ACCESS_TIER("INSUFFICIENT_ACCESS_TIER");

    private final String code;

    DefaultErrorCodes(String code) {
        this.code = code;
    }

    @Override
    public String toCode() {
        return code;
    }

}
